# Netlify configuration for Angular project
[build]
  # Base directory for the build (where package.json is located for Angular)
  base = "angular/"
  
  # Build command for Angular production build with optimization
  command = "npm ci && npm run build -- --configuration=production"
  
  # Directory to publish (Angular dist folder)
  publish = "dist/ai-agent-dashboard-angular"

# Build environment settings
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA redirect rules for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Branch-specific builds
[context.production]
  command = "npm ci && npm run build -- --configuration=production"

[context.deploy-preview]
  command = "npm ci && npm run build -- --configuration=production"

[context.branch-deploy]
  command = "npm ci && npm run build -- --configuration=production"

# Development context (if needed)
[context.dev]
  command = "npm ci && npm run build"

# Functions (if needed in the future)
[functions]
  directory = "netlify/functions"

# Forms (if needed)
[forms]
  # Enable Netlify Forms if you add contact forms later